Algoritmo "concatenação"

// Descrição   : concatenação
// Autor(a)    : kissimilene oliveira
// Data atual  : 30/07/2021
Var
// Seção de Declarações das variáveis 
    nome : caractere
    numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("digite o nome")
   leia(nome)
   escreval("digite um numero")
   leia(numero)

   escreval(nome, " : ", numero)

Fimalgoritmo