Algoritmo "Entrada e saidas de dados"

// Descrição   : Entrada e saidas de dados
// Autor(a)    : kissimilene oliveira
// Data atual  : 29/07/2021
Var
// Seção de Declarações das variáveis 
   nome: caractere
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite seu nome?")
   leia(nome)
   escreval("digite sua idade?")
   leia(nota)
   
   escreval("O nome digitado foi!" ,nome)
   escreval("A sua idade é!",nota)

Fimalgoritmo